Set minimum version requirements for "diffusers"
Lower versions throw ImportErrors because of missing classes in diffusers.image_processor

Example: ImportError: cannot import name 'PipelineImageInput' from 'diffusers.image_processor'